package support

//---------------------------------------------------------------------

// ProjectionTableEntry holds a projection entry
type ProjectionTableEntry struct {
	ID          string
	Description string
}

// ProjectionsTable is the global list of projections
var ProjectionsTable = map[string]*ProjectionTableEntry{
	"aea":         &ProjectionTableEntry{"aea", "Albers Equal Area"},
	"aeqd":        &ProjectionTableEntry{"aeqd", "Azimuthal Equidistant"},
	"airy":        &ProjectionTableEntry{"airy", "Airy"},
	"aitoff":      &ProjectionTableEntry{"aitoff", "Aitoff"},
	"alsk":        &ProjectionTableEntry{"alsk", "Mod. Stererographics of Alaska"},
	"apian":       &ProjectionTableEntry{"apian", "Apian Globular I"},
	"august":      &ProjectionTableEntry{"august", "August Epicycloidal"},
	"axisswap":    &ProjectionTableEntry{"axisswap", "Axis ordering"},
	"bacon":       &ProjectionTableEntry{"bacon", "Bacon Globular"},
	"bipc":        &ProjectionTableEntry{"bipc", "Bipolar conic of western hemisphere"},
	"boggs":       &ProjectionTableEntry{"boggs", "Boggs Eumorphic"},
	"bonne":       &ProjectionTableEntry{"bonne", "Bonne (Werner lat_1=90)"},
	"calcofi":     &ProjectionTableEntry{"calcofi", "Cal Coop Ocean Fish Invest Lines/Stations"},
	"cart":        &ProjectionTableEntry{"cart", "Geodetic/cartesian conversions"},
	"cass":        &ProjectionTableEntry{"cass", "Cassini"},
	"cc":          &ProjectionTableEntry{"cc", "Central Cylindrical"},
	"ccon":        &ProjectionTableEntry{"ccon", "Central Conic"},
	"cea":         &ProjectionTableEntry{"cea", "Equal Area Cylindrical"},
	"chamb":       &ProjectionTableEntry{"chamb", "Chamberlin Trimetric"},
	"collg":       &ProjectionTableEntry{"collg", "Collignon"},
	"comill":      &ProjectionTableEntry{"comill", "Compact Miller"},
	"crast":       &ProjectionTableEntry{"crast", "Craster Parabolic (Putnins P4)"},
	"deformation": &ProjectionTableEntry{"deformation", "Kinematic grid shift"},
	"denoy":       &ProjectionTableEntry{"denoy", "Denoyer Semi-Elliptical"},
	"eck1":        &ProjectionTableEntry{"eck1", "Eckert I"},
	"eck2":        &ProjectionTableEntry{"eck2", "Eckert II"},
	"eck3":        &ProjectionTableEntry{"eck3", "Eckert III"},
	"eck4":        &ProjectionTableEntry{"eck4", "Eckert IV"},
	"eck5":        &ProjectionTableEntry{"eck5", "Eckert V"},
	"eck6":        &ProjectionTableEntry{"eck6", "Eckert VI"},
	"eqc":         &ProjectionTableEntry{"eqc", "Equidistant Cylindrical (Plate Caree)"},
	"eqdc":        &ProjectionTableEntry{"eqdc", "Equidistant Conic"},
	"euler":       &ProjectionTableEntry{"euler", "Euler"},
	"etmerc":      &ProjectionTableEntry{"etmerc", "Extended Transverse Mercator"},
	"fahey":       &ProjectionTableEntry{"fahey", "Fahey"},
	"fouc":        &ProjectionTableEntry{"fouc", "Foucaut"},
	"fouc_s":      &ProjectionTableEntry{"fouc_s", "Foucaut Sinusoidal"},
	"gall":        &ProjectionTableEntry{"gall", "Gall (Gall Stereographic)"},
	"geoc":        &ProjectionTableEntry{"geoc", "Geocentric Latitude"},
	"geocent":     &ProjectionTableEntry{"geocent", "Geocentric"},
	"geos":        &ProjectionTableEntry{"geos", "Geostationary Satellite View"},
	"gins8":       &ProjectionTableEntry{"gins8", "Ginsburg VIII (TsNIIGAiK)"},
	"gn_sinu":     &ProjectionTableEntry{"gn_sinu", "General Sinusoidal Series"},
	"gnom":        &ProjectionTableEntry{"gnom", "Gnomonic"},
	"goode":       &ProjectionTableEntry{"goode", "Goode Homolosine"},
	"gs48":        &ProjectionTableEntry{"gs48", "Mod. Stererographics of 48 U.S."},
	"gs50":        &ProjectionTableEntry{"gs50", "Mod. Stererographics of 50 U.S."},
	"hammer":      &ProjectionTableEntry{"hammer", "Hammer & Eckert-Greifendorff"},
	"hatano":      &ProjectionTableEntry{"hatano", "Hatano Asymmetrical Equal Area"},
	"healpix":     &ProjectionTableEntry{"healpix", "HEALPix"},
	"rhealpix":    &ProjectionTableEntry{"rhealpix", "rHEALPix"},
	"helmert":     &ProjectionTableEntry{"helmert", "3- and 7-parameter Helmert shift"},
	"hgridshift":  &ProjectionTableEntry{"hgridshift", "Horizontal grid shift"},
	"horner":      &ProjectionTableEntry{"horner", "Horner polynomial evaluation"},
	"igh":         &ProjectionTableEntry{"igh", "Interrupted Goode Homolosine"},
	"imw_p":       &ProjectionTableEntry{"imw_p", "International Map of the World Polyconic"},
	"isea":        &ProjectionTableEntry{"isea", "Icosahedral Snyder Equal Area"},
	"kav5":        &ProjectionTableEntry{"kav5", "Kavraisky V"},
	"kav7":        &ProjectionTableEntry{"kav7", "Kavraisky VII"},
	"krovak":      &ProjectionTableEntry{"krovak", "Krovak"},
	"labrd":       &ProjectionTableEntry{"labrd", "Laborde"},
	"laea":        &ProjectionTableEntry{"laea", "Lambert Azimuthal Equal Area"},
	"lagrng":      &ProjectionTableEntry{"lagrng", "Lagrange"},
	"larr":        &ProjectionTableEntry{"larr", "Larrivee"},
	"lask":        &ProjectionTableEntry{"lask", "Laskowski"},
	"lonlat":      &ProjectionTableEntry{"lonlat", "Lat/long (Geodetic)"},
	"latlon":      &ProjectionTableEntry{"latlon", "Lat/long (Geodetic alias)"},
	"latlong":     &ProjectionTableEntry{"latlong", "Lat/long (Geodetic alias)"},
	"longlat":     &ProjectionTableEntry{"longlat", "Lat/long (Geodetic alias)"},
	"lcc":         &ProjectionTableEntry{"lcc", "Lambert Conformal Conic"},
	"lcca":        &ProjectionTableEntry{"lcca", "Lambert Conformal Conic Alternative"},
	"leac":        &ProjectionTableEntry{"leac", "Lambert Equal Area Conic"},
	"lee_os":      &ProjectionTableEntry{"lee_os", "Lee Oblated Stereographic"},
	"loxim":       &ProjectionTableEntry{"loxim", "Loximuthal"},
	"lsat":        &ProjectionTableEntry{"lsat", "Space oblique for LANDSAT"},
	"mbt_s":       &ProjectionTableEntry{"mbt_s", "McBryde-Thomas Flat-Polar Sine"},
	"mbt_fps":     &ProjectionTableEntry{"mbt_fps", "McBryde-Thomas Flat-Pole Sine (No. 2)"},
	"mbtfpp":      &ProjectionTableEntry{"mbtfpp", "McBride-Thomas Flat-Polar Parabolic"},
	"mbtfpq":      &ProjectionTableEntry{"mbtfpq", "McBryde-Thomas Flat-Polar Quartic"},
	"mbtfps":      &ProjectionTableEntry{"mbtfps", "McBryde-Thomas Flat-Polar Sinusoidal"},
	"merc":        &ProjectionTableEntry{"merc", "Mercator"},
	"mil_os":      &ProjectionTableEntry{"mil_os", "Miller Oblated Stereographic"},
	"mill":        &ProjectionTableEntry{"mill", "Miller Cylindrical"},
	"misrsom":     &ProjectionTableEntry{"misrsom", "Space oblique for MISR"},
	"moll":        &ProjectionTableEntry{"moll", "Mollweide"},
	"molodensky":  &ProjectionTableEntry{"molodensky", "Molodensky transform"},
	"murd1":       &ProjectionTableEntry{"murd1", "Murdoch I"},
	"murd2":       &ProjectionTableEntry{"murd2", "Murdoch II"},
	"murd3":       &ProjectionTableEntry{"murd3", "Murdoch III"},
	"natearth":    &ProjectionTableEntry{"natearth", "Natural Earth"},
	"natearth2":   &ProjectionTableEntry{"natearth2", "Natural Earth II"},
	"nell":        &ProjectionTableEntry{"nell", "Nell"},
	"nell_h":      &ProjectionTableEntry{"nell_h", "Nell-Hammer"},
	"nicol":       &ProjectionTableEntry{"nicol", "Nicolosi Globular"},
	"nsper":       &ProjectionTableEntry{"nsper", "Near-sided perspective"},
	"nzmg":        &ProjectionTableEntry{"nzmg", "New Zealand Map Grid"},
	"ob_tran":     &ProjectionTableEntry{"ob_tran", "General Oblique Transformation"},
	"ocea":        &ProjectionTableEntry{"ocea", "Oblique Cylindrical Equal Area"},
	"oea":         &ProjectionTableEntry{"oea", "Oblated Equal Area"},
	"omerc":       &ProjectionTableEntry{"omerc", "Oblique Mercator"},
	"ortel":       &ProjectionTableEntry{"ortel", "Ortelius Oval"},
	"ortho":       &ProjectionTableEntry{"ortho", "Orthographic"},
	"pconic":      &ProjectionTableEntry{"pconic", "Perspective Conic"},
	"patterson":   &ProjectionTableEntry{"patterson", "Patterson Cylindrical"},
	"pipeline":    &ProjectionTableEntry{"pipeline", "Transformation pipeline manager"},
	"poly":        &ProjectionTableEntry{"poly", "Polyconic (American)"},
	"putp1":       &ProjectionTableEntry{"putp1", "Putnins P1"},
	"putp2":       &ProjectionTableEntry{"putp2", "Putnins P2"},
	"putp3":       &ProjectionTableEntry{"putp3", "Putnins P3"},
	"putp3p":      &ProjectionTableEntry{"putp3p", "Putnins P3'"},
	"putp4p":      &ProjectionTableEntry{"putp4p", "Putnins P4'"},
	"putp5":       &ProjectionTableEntry{"putp5", "Putnins P5"},
	"putp5p":      &ProjectionTableEntry{"putp5p", "Putnins P5'"},
	"putp6":       &ProjectionTableEntry{"putp6", "Putnins P6"},
	"putp6p":      &ProjectionTableEntry{"putp6p", "Putnins P6'"},
	"qua_aut":     &ProjectionTableEntry{"qua_aut", "Quartic Authalic"},
	"qsc":         &ProjectionTableEntry{"qsc", "Quadrilateralized Spherical Cube"},
	"robin":       &ProjectionTableEntry{"robin", "Robinson"},
	"rouss":       &ProjectionTableEntry{"rouss", "Roussilhe Stereographic"},
	"rpoly":       &ProjectionTableEntry{"rpoly", "Rectangular Polyconic"},
	"sch":         &ProjectionTableEntry{"sch", "Spherical Cross-track Height"},
	"sinu":        &ProjectionTableEntry{"sinu", "Sinusoidal (Sanson-Flamsteed)"},
	"somerc":      &ProjectionTableEntry{"somerc", "Swiss. Obl. Mercator"},
	"stere":       &ProjectionTableEntry{"stere", "Stereographic"},
	"sterea":      &ProjectionTableEntry{"sterea", "Oblique Stereographic Alternative"},
	"gstmerc":     &ProjectionTableEntry{"gstmerc", "Gauss-Schreiber Transverse Mercator (aka Gauss-Laborde Reunion)"},
	"tcc":         &ProjectionTableEntry{"tcc", "Transverse Central Cylindrical"},
	"tcea":        &ProjectionTableEntry{"tcea", "Transverse Cylindrical Equal Area"},
	"times":       &ProjectionTableEntry{"times", "Times Projection"},
	"tissot":      &ProjectionTableEntry{"tissot", "Tissot Conic"},
	"tmerc":       &ProjectionTableEntry{"tmerc", "Transverse Mercator"},
	"tpeqd":       &ProjectionTableEntry{"tpeqd", "Two Point Equidistant"},
	"tpers":       &ProjectionTableEntry{"tpers", "Tilted perspective"},
	"unitconvert": &ProjectionTableEntry{"unitconvert", "Unit conversion"},
	"ups":         &ProjectionTableEntry{"ups", "Universal Polar Stereographic"},
	"urm5":        &ProjectionTableEntry{"urm5", "Urmaev V"},
	"urmfps":      &ProjectionTableEntry{"urmfps", "Urmaev Flat-Polar Sinusoidal"},
	"utm":         &ProjectionTableEntry{"utm", "Universal Transverse Mercator (UTM)"},
	"vandg":       &ProjectionTableEntry{"vandg", "van der Grinten (I)"},
	"vandg2":      &ProjectionTableEntry{"vandg2", "van der Grinten II"},
	"vandg3":      &ProjectionTableEntry{"vandg3", "van der Grinten III"},
	"vandg4":      &ProjectionTableEntry{"vandg4", "van der Grinten IV"},
	"vitk1":       &ProjectionTableEntry{"vitk1", "Vitkovsky I"},
	"vgridshift":  &ProjectionTableEntry{"vgridshift", "Vertical grid shift"},
	"wag1":        &ProjectionTableEntry{"wag1", "Wagner I (Kavraisky VI)"},
	"wag2":        &ProjectionTableEntry{"wag2", "Wagner II"},
	"wag3":        &ProjectionTableEntry{"wag3", "Wagner III"},
	"wag4":        &ProjectionTableEntry{"wag4", "Wagner IV"},
	"wag5":        &ProjectionTableEntry{"wag5", "Wagner V"},
	"wag6":        &ProjectionTableEntry{"wag6", "Wagner VI"},
	"wag7":        &ProjectionTableEntry{"wag7", "Wagner VII"},
	"weren":       &ProjectionTableEntry{"weren", "Werenskiold I"},
	"wink1":       &ProjectionTableEntry{"wink1", "Winkel I"},
	"wink2":       &ProjectionTableEntry{"wink2", "Winkel II"},
	"wintri":      &ProjectionTableEntry{"wintri", "Winkel Tripel"},
}
